"""
Class object for Response
Documentation: https://system-bridge.timmo.dev

Generated by generator/generator.py - 2021-02-20 16:57:03.395502
"""
from .base import BridgeBase


class Response(BridgeBase):
    @property
    def command(self):
        return self.attributes.get("command", "")

    @property
    def arguments(self):
        return self.attributes.get("arguments", [])

    @property
    def wait(self):
        return self.attributes.get("wait", True)

    @property
    def success(self):
        return self.attributes.get("success", True)

    @property
    def message(self):
        return self.attributes.get("message", "")
