"""
Generated by generator/generator.py - 2021-02-20 16:53:35.135485
"""
from systembridge.objects.command.payload import Payload
from tests.responses.command.payload_fixture import payload_fixture_response


def test_payload(payload_fixture_response):
    obj = Payload(payload_fixture_response)
    assert obj.command == payload_fixture_response["command"]
    assert obj.arguments[0] == payload_fixture_response["arguments"][0]
    assert obj.wait == payload_fixture_response["wait"]
