"""
Generated by generator/generator.py - 2021-02-20 16:48:42.854477
"""
import pytest


@pytest.fixture()
def audio_fixture_response():
    return {'id': 'ROOTBridgeMEDIABridge0000', 'name': 'Oculus Virtual Audio Device', 'manufacturer': 'Oculus', 'revision': '', 'driver': '', 'default': '', 'channel': '', 'type': '', 'in': '', 'out': '', 'status': '3'}
