"""
Generated by generator/generator.py - 2021-02-20 16:50:21.146717
"""
import pytest


@pytest.fixture()
def bluetooth_fixture_response():
    return {'device': '', 'name': 'Headset Audio Gateway Service', 'manufacturer': 'Microsoft', 'macDevice': '', 'macHost': '', 'batteryPercent': '', 'type': 'Headset', 'connected': ''}
