"""
Generated by generator/generator.py - 2021-02-20 16:49:35.219445
"""
from systembridge.objects.battery import BridgeBattery
from tests.responses.battery_fixture import battery_fixture_response

def test_battery(battery_fixture_response):
    obj = BridgeBattery(battery_fixture_response)
    assert obj.hasBattery == battery_fixture_response['hasBattery']
    assert obj.cycleCount == battery_fixture_response['cycleCount']
    assert obj.isCharging == battery_fixture_response['isCharging']
    assert obj.designedCapacity == battery_fixture_response['designedCapacity']
    assert obj.maxCapacity == battery_fixture_response['maxCapacity']
    assert obj.currentCapacity == battery_fixture_response['currentCapacity']
    assert obj.voltage == battery_fixture_response['voltage']
    assert obj.capacityUnit == battery_fixture_response['capacityUnit']
    assert obj.percent == battery_fixture_response['percent']
    assert obj.timeRemaining == battery_fixture_response['timeRemaining']
    assert obj.acConnected == battery_fixture_response['acConnected']
    assert obj.type == battery_fixture_response['type']
    assert obj.model == battery_fixture_response['model']
    assert obj.manufacturer == battery_fixture_response['manufacturer']
    assert obj.serial == battery_fixture_response['serial']
