"""
Generated by generator/generator.py - 2021-02-20 17:09:39.232395
"""
from systembridge.objects.system import System
from tests.fixtrues.system_fixtrue import system_fixtrue_response


def test_system(system_fixtrue_response):
    obj = System(system_fixtrue_response)
    assert (
        obj.baseboard.manufacturer
        == system_fixtrue_response["baseboard"]["manufacturer"]
    )
    assert obj.baseboard.model == system_fixtrue_response["baseboard"]["model"]
    assert obj.baseboard.version == system_fixtrue_response["baseboard"]["version"]
    assert obj.baseboard.serial == system_fixtrue_response["baseboard"]["serial"]
    assert obj.baseboard.assetTag == system_fixtrue_response["baseboard"]["assetTag"]
    assert obj.baseboard.memMax == system_fixtrue_response["baseboard"]["memMax"]
    assert obj.baseboard.memSlots == system_fixtrue_response["baseboard"]["memSlots"]
    assert obj.bios.vendor == system_fixtrue_response["bios"]["vendor"]
    assert obj.bios.version == system_fixtrue_response["bios"]["version"]
    assert obj.bios.releaseDate == system_fixtrue_response["bios"]["releaseDate"]
    assert obj.bios.revision == system_fixtrue_response["bios"]["revision"]
    assert (
        obj.chassis.manufacturer == system_fixtrue_response["chassis"]["manufacturer"]
    )
    assert obj.chassis.model == system_fixtrue_response["chassis"]["model"]
    assert obj.chassis.type == system_fixtrue_response["chassis"]["type"]
    assert obj.chassis.version == system_fixtrue_response["chassis"]["version"]
    assert obj.chassis.serial == system_fixtrue_response["chassis"]["serial"]
    assert obj.chassis.assetTag == system_fixtrue_response["chassis"]["assetTag"]
    assert obj.chassis.sku == system_fixtrue_response["chassis"]["sku"]
    assert obj.system.manufacturer == system_fixtrue_response["system"]["manufacturer"]
    assert obj.system.model == system_fixtrue_response["system"]["model"]
    assert obj.system.version == system_fixtrue_response["system"]["version"]
    assert obj.system.serial == system_fixtrue_response["system"]["serial"]
    assert obj.system.uuid == system_fixtrue_response["system"]["uuid"]
    assert obj.system.sku == system_fixtrue_response["system"]["sku"]
    assert obj.system.virtual == system_fixtrue_response["system"]["virtual"]
    assert obj.uuid.os == system_fixtrue_response["uuid"]["os"]
    assert obj.uuid.hardware == system_fixtrue_response["uuid"]["hardware"]
    assert obj.uuid.macs[0] == system_fixtrue_response["uuid"]["macs"][0]
