"""
Generated by generator/generator.py - 2021-02-20 17:09:12.868028
"""
from systembridge.objects.os import Os
from tests.fixtrues.os_fixtrue import os_fixtrue_response


def test_os(os_fixtrue_response):
    obj = Os(os_fixtrue_response)
    assert obj.platform == os_fixtrue_response["platform"]
    assert obj.distro == os_fixtrue_response["distro"]
    assert obj.release == os_fixtrue_response["release"]
    assert obj.codename == os_fixtrue_response["codename"]
    assert obj.kernel == os_fixtrue_response["kernel"]
    assert obj.arch == os_fixtrue_response["arch"]
    assert obj.hostname == os_fixtrue_response["hostname"]
    assert obj.fqdn == os_fixtrue_response["fqdn"]
    assert obj.codepage == os_fixtrue_response["codepage"]
    assert obj.logofile == os_fixtrue_response["logofile"]
    assert obj.serial == os_fixtrue_response["serial"]
    assert obj.build == os_fixtrue_response["build"]
    assert obj.servicepack == os_fixtrue_response["servicepack"]
    assert obj.uefi == os_fixtrue_response["uefi"]
    assert obj.hypervisor == os_fixtrue_response["hypervisor"]
    assert obj.remoteSession == os_fixtrue_response["remoteSession"]
    assert obj.users[0].user == os_fixtrue_response["users"][0]["user"]
    assert obj.users[0].tty == os_fixtrue_response["users"][0]["tty"]
    assert obj.users[0].date == os_fixtrue_response["users"][0]["date"]
    assert obj.users[0].time == os_fixtrue_response["users"][0]["time"]
    assert obj.users[0].ip == os_fixtrue_response["users"][0]["ip"]
    assert obj.users[0].command == os_fixtrue_response["users"][0]["command"]
