"""
Generated by generator/generator.py - 2021-02-20 16:41:50.490343
"""
from systembridge.objects.information import BridgeInformation
from tests.responses.information_fixture import information_fixture_response


def test_information(information_fixture_response):
    obj = BridgeInformation(information_fixture_response)
    assert obj.audio.description == information_fixture_response["audio"]["description"]
    assert obj.audio.endpoint == information_fixture_response["audio"]["endpoint"]
    assert (
        obj.battery.description
        == information_fixture_response["battery"]["description"]
    )
    assert obj.battery.endpoint == information_fixture_response["battery"]["endpoint"]
    assert (
        obj.bluetooth.description
        == information_fixture_response["bluetooth"]["description"]
    )
    assert (
        obj.bluetooth.endpoint == information_fixture_response["bluetooth"]["endpoint"]
    )
    assert (
        obj.command.description
        == information_fixture_response["command"]["description"]
    )
    assert obj.command.endpoint == information_fixture_response["command"]["endpoint"]
    assert obj.cpu.description == information_fixture_response["cpu"]["description"]
    assert obj.cpu.endpoint == information_fixture_response["cpu"]["endpoint"]
    assert obj.docs.description == information_fixture_response["docs"]["description"]
    assert obj.docs.endpoint == information_fixture_response["docs"]["endpoint"]
    assert (
        obj.filesystem.description
        == information_fixture_response["filesystem"]["description"]
    )
    assert (
        obj.filesystem.endpoint
        == information_fixture_response["filesystem"]["endpoint"]
    )
    assert (
        obj.graphics.description
        == information_fixture_response["graphics"]["description"]
    )
    assert obj.graphics.endpoint == information_fixture_response["graphics"]["endpoint"]
    assert (
        obj.information.description
        == information_fixture_response["information"]["description"]
    )
    assert (
        obj.information.endpoint
        == information_fixture_response["information"]["endpoint"]
    )
    assert (
        obj.memory.description == information_fixture_response["memory"]["description"]
    )
    assert obj.memory.endpoint == information_fixture_response["memory"]["endpoint"]
    assert (
        obj.network.description
        == information_fixture_response["network"]["description"]
    )
    assert obj.network.endpoint == information_fixture_response["network"]["endpoint"]
    assert obj.os.description == information_fixture_response["os"]["description"]
    assert obj.os.endpoint == information_fixture_response["os"]["endpoint"]
    assert (
        obj.system.description == information_fixture_response["system"]["description"]
    )
    assert obj.system.endpoint == information_fixture_response["system"]["endpoint"]
