"""
Class object for KeyboardResponse
Documentation: https://system-bridge.timmo.dev

Generated by generator/generator.py - 2021-02-20 16:57:03.395502
"""
from .payload import KeyboardPayload


class KeyboardResponse(KeyboardPayload):
    def __init__(self, payload=None):
        super().__init__(payload)
