{
    "controllers": [
        {
            "vendor": "NVIDIA",
            "model": "NVIDIA GeForce RTX 3070",
            "bus": "PCI",
            "vram": 8192,
            "vramDynamic": false,
            "subDeviceId": "0x40691458",
            "driverVersion": "461.40",
            "name": "GeForce RTX 3070",
            "pciBus": "00000000:0A:00.0",
            "memoryTotal": 8192,
            "memoryUsed": 2989,
            "memoryFree": 5203,
            "utilizationGpu": 12,
            "utilizationMemory": 15,
            "temperatureGpu": 49,
            "powerDraw": 38.94,
            "powerLimit": 300,
            "clockCore": 480,
            "clockMemory": 810,
        }
    ],
    "displays": [
        {
            "vendor": "(Standard monitor types)",
            "model": "Generic PnP Monitor",
            "deviceName": "SPLAY1",
            "main": true,
            "builtin": false,
            "connection": "DP",
            "resolutionX": 2560,
            "resolutionY": 1440,
            "sizeX": 60,
            "sizeY": 34,
            "pixelDepth": "32",
            "currentResX": 2560,
            "currentResY": 1440,
            "positionX": 0,
            "positionY": 0,
        },
        {
            "vendor": "",
            "model": "",
            "deviceName": "DISPLAY2",
            "main": false,
            "builtin": false,
            "connection": "DP",
            "resolutionX": 2560,
            "resolutionY": 1440,
            "sizeX": 60,
            "sizeY": 34,
            "pixelDepth": "32",
            "currentResX": 2560,
            "currentResY": 1440,
            "positionX": 2560,
            "positionY": 0,
        },
    ],
}
