"""
Generated by generator/generator.py - 2021-02-20 16:53:35.135485
"""
import pytest


@pytest.fixture()
def payload_fixture_response():
    return {"command": "python", "arguments": ["-V"], "wait": True}
